feat: support multiple rollup chain IDs
alt-research/mach-avs pull request #138
Opened 2024-05-16 06:20 UTC by ny-alt

This PR closes #136.

2024-05-16 09:46 UTC, bb111189 requested changes

2024-05-16 09:46 UTC, bb111189 commented on contracts/src/core/MachServiceManager.sol
> +        uint256 rollupChainId,
add a check to check whether rollupchainid provided is known or not. If not known, revert

2024-05-16 10:34 UTC, ny-alt commented on contracts/src/core/MachServiceManager.sol
> +        uint256 rollupChainId,
applied `onlyValidRollupChainID` modifier to `confirmAlert` and  `removeAlert` functions.

2024-05-17 02:18 UTC, bb111189 approved these changes

2024-05-17 02:19 UTC, merged