feat: deregister
alt-research/mach-avs pull request #155
Opened 2024-06-07 03:28 UTC by ny-alt

This PR adds a function to deregister a service manager.

2024-06-07 06:14 UTC, bb111189 requested changes

2024-06-07 06:14 UTC, bb111189 commented on contracts/src/core/MachOptimismZkServiceManager.sol
> -            revert NotInAllowlist();
acccidental commit?

2024-06-07 06:15 UTC, ny-alt commented on contracts/src/core/MachOptimismZkServiceManager.sol
> -            revert NotInAllowlist();
Renaming the error

2024-06-10 02:24 UTC, bb111189 approved these changes

2024-06-10 02:24 UTC, merged